# R repository
repository="http://cran.us.r-project.org"
# Install packages
install.packages('data.table', repos=repository)
install.packages('stringr', repos=repository)
install.packages('ggplot2', repos=repository)
install.packages('extrafont', repos=repository)
install.packages('irr', repos=repository)
install.packages('caret', repos=repository)
install.packages('ltm', repos=repository)
install.packages('rcompanion', repos=repository)
install.packages('agricolae', repos=repository)
install.packages('nortest', repos=repository)
install.packages('effsize', repos=repository)
# Load libraries (aka runtime sanity check)
library('data.table')
library('stringr')
library('ggplot2')
library('extrafont')
library('irr')
library('caret')
library('ltm')
library('rcompanion')
library('agricolae')
library('nortest')
library('effsize')
# Exit
quit(save="no", status=0)
